---
- include_tasks: setup-debian.yml
  when: ansible_distribution == 'Debian'
- include_tasks: setup-ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: Fix /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^(127.0.1.1\s+)'
    line: '\1{{ hostname }}'
    backrefs: true

- name: Install puppet-agent
  ansible.builtin.package:
    name: puppet
    state: present

- name: Set puppet5.den as master
  ansible.builtin.lineinfile:
    path: /etc/puppet/puppet.conf
    search_string: 'server = puppet5.den'
    insertbefore: '^\[main\]$'
    line: "server = puppet5.den\n"

- name: Check puppet lib directory
  ansible.builtin.find:
    path: /var/lib/puppet
  register: lib_puppet_dir

- name: Run puppet-agent (network)
  ansible.builtin.command:
    cmd: puppet agent --test --tags network
  register: agent_result
  retries: 5
  failed_when: agent_result.rc not in (0, 2)
  when: lib_puppet_dir.matched == 0

- name: Upgrade system packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: full

- name: Reboot
  ansible.builtin.reboot:
    reboot_command: systemctl reboot
    reboot_timeout: 180
