---
- hosts: rpi4_poe
  roles:
    - rpi-poe
    - base-os
- hosts: ubuntu
  gather_facts: no
  roles:
    - role: lxc-preprovision
      tags: lxc
      vars:
        # Note: Variables do leak between roles, so this is one of the few safe places where we can override what we
        # need per role without being worried.
        ansible_host: "{{ lxd_host }}"
        ansible_user: null
        lxc_default_user: ubuntu
        provision_ssh_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGeX/9uo92CUV0spOD/lhwHUIJ40kxq4BY/NjqdVVhxb"
    - role: base-os
      tags: base
      vars:
        ansible_host: "{{ inventory_hostname }}"
        ansible_password: null
        ansible_user: ubuntu
        is_lxc: true
