---
- name: Enable PoE overlay
  ansible.builtin.lineinfile:
    path: /boot/config.txt
    search_string: dtoverlay=rpi-poe
    insertafter: '^# Additional overlays'
    line: dtoverlay=rpi-poe
  register: boot_params

- name: Enable cgroups in kernel cmdline
  ansible.builtin.lineinfile:
    path: /boot/cmdline.txt
    regexp: '^console=(.+ rootwait)$'
    line: 'console=\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
    backrefs: yes
  register: boot_params

- name: Reboot to apply kernel cmdline
  ansible.builtin.reboot:
  when: boot_params.changed
