- hosts: lxcs
  gather_facts: false
  roles:
    - role: lxc-preprovision
      tags: pre
    - role: base-os
  vars:
    ansible_host: "{{ lxd_host }}"
    is_lxc: true
    hostname: "{{ inventory_hostname_short }}"
