---
- name: Install Puppet master and git
  ansible.builtin.package:
    name:
      - puppet-master
      - git
    state: present

- name: Create directory for eyaml keys
  ansible.builtin.file:
    path: "{{ puppet_home_dir }}/keys"
    state: directory
    owner: puppet
    group: puppet
    mode: '0755'

- name: Deploy eyaml keys
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ puppet_home_dir }}/keys/"
    owner: puppet
    group: puppet
    mode: '0700'
  diff: false
  loop:
    - private_key.pkcs7.pem
    - public_key.pkcs7.pem
  notify:
    - Restart puppet-master

- name: Is /etc/puppet a repository?
  ansible.builtin.stat:
    path: /etc/puppet/.git
  register: puppet_git_stat

- name: Backup the default Puppet directory
  ansible.builtin.command:
    cmd: mv /etc/puppet /etc/puppet.bak
  when: not puppet_git_stat.stat.exists

- name: Puppet repository git checkout
  ansible.builtin.git:
    repo: 'https://gitlab.com/jkrcma/puppet-home.git'
    dest: /etc/puppet
    separate_git_dir: /opt/puppet.git
  notify:
    - Restart puppet-master

- name: Set up .ssh directory
  ansible.builtin.file:
    path: "{{ puppet_home_dir }}/.ssh"
    state: directory
    owner: puppet
    group: puppet
    mode: '0700'

- name: Deploy SSH key for CA sync
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ puppet_home_dir }}/.ssh/{{ item }}"
    owner: puppet
    group: puppet
    mode: '0600'
  diff: false
  loop:
    - id_ed25519
    - id_ed25519.pub
