---
- name: Install Puppet master, r10k and git
  ansible.builtin.package:
    name:
      - puppet-master
      - git
      - r10k
    state: present

- name: Create directory for eyaml keys
  ansible.builtin.file:
    path: "{{ puppet_home_dir }}/keys"
    state: directory
    owner: puppet
    group: puppet
    mode: '0755'

- name: Deploy eyaml keys
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ puppet_home_dir }}/keys/"
    owner: puppet
    group: puppet
    mode: '0600'
  diff: false
  loop:
    - private_key.pkcs7.pem
    - public_key.pkcs7.pem
  notify:
    - Restart puppet-master

- name: Set up .ssh directory
  ansible.builtin.file:
    path: "{{ puppet_home_dir }}/.ssh"
    state: directory
    owner: puppet
    group: puppet
    mode: '0700'

- name: Deploy SSH key for CA sync
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ puppet_home_dir }}/.ssh/{{ item }}"
    owner: puppet
    group: puppet
    mode: '0600'
  diff: false
  loop:
    - id_ed25519
    - id_ed25519.pub

- name: Deploy Puppet and r10k
  tags: deploy_puppet
  block:
  - name: Create r10k directory
    ansible.builtin.file:
      path: /etc/puppetlabs/r10k
      state: directory
      recurse: true

  - name: r10k repository git checkout
    ansible.builtin.git:
      repo: 'https://gitlab.com/home-taiku-cz/puppetmaster-r10k.git'
      dest: /etc/puppetlabs/r10k
      separate_git_dir: /opt/puppetmaster-r10k.git

  - name: Deploy puppet-master configuration
    ansible.builtin.copy:
      src: /etc/puppetlabs/r10k/puppet.conf
      dest: /etc/puppet/puppet.conf
      remote_src: true
    notify:
      - Restart puppet-master

  - name: Deploy External Node Classifier
    ansible.builtin.copy:
      src: "/etc/puppetlabs/r10k/{{ item }}"
      dest: "/etc/puppet/{{ item }}"
      remote_src: true
    loop:
      - enc.py
      - nodes.yaml

  - name: Deploy Puppetfile
    ansible.builtin.copy:
      src: /etc/puppetlabs/r10k/Puppetfile
      dest: /etc/puppet/Puppetfile
      remote_src: true
    register: puppetfile

  - name: Install & purge Puppet forge modules
    ansible.builtin.shell:
      cmd: |
        r10k puppetfile install
        r10k puppetfile purge
      chdir: /etc/puppet
    when: puppetfile.changed

  - name: Deploy environments with r10k
    ansible.builtin.command:
      cmd: r10k deploy environment
